### ISSUE TITLE
investigate feasibility of text-based UI

### ISSUE THREAD

**Issue by turtlefarmer** [turtlefarmer/codeu_project_2017#3]
Primarily, how easy is it to segment different sections of a java console application and have scrolling chat text not interfere with input section.

**Comment by rshar1** [comment]
From what I've found so far, there are several options to get this done:
1. We can change the terminal settings to raw mode in order to retrieve input on each character. This is platform dependent so the least feasible. [stty command on linux](http://man7.org/linux/man-pages/man1/stty.1.html)
2. Use a library like [Lanterna](https://github.com/mabe02/lanterna). This library would likely use swing to make a terminal-like window. It would also be portable since it is written completely in java.
3. We can create a very simple JavaFX UI that would likely just have a text field and a text area. This would simply separate the input from the output. We could also add a simple way to navigate conversations.

**Comment by turtlefarmer** [comment]
1) If it's just 100% raw mode (as in, print char c on coord x,y), I recommend staying  away from this option.  Implemetning word wrapping and scrolling does not sound fun :( 

No real opinion between #2 and #3 right now, I need to get my java dev env setup and play around with lanterna a little bit, will try to do that soon.

**Comment by turtlefarmer** [comment]
We decided we're moving away from a text-only UI and will be building a GUI, most likely in JavaFX.
